APPLICATION_NAME = 'HAMLOG Agent'
APPLICATION_ORGANIZATION_NAME = 'HAMLOG LLC'
APPLICATION_ORGANIZATION_DOMAIN = 'com.hamlog.agent'
APPLICATION_VERSION = '0.0.3'

APPLICATION_LOG_FILE_NAME = 'hamlog-agent-log.txt'
APPLICATION_LOG_FORMAT = '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
from logging import DEBUG as APPLICATION_LOG_LEVEL
